### ISSUE TITLE
v25.2.0 - Caught DependencyError: 'TTSManager' object has no attribute 'coqui_tts_load_custom'

### ISSUE THREAD

**Issue by alexanderjacuna** [DrewThomasson/ebook2audiobook#270]
### Summary:
Looks like there is throwing a no attribute error when attempting to use a custom model with a small text file for testing. Model .zip file is using the recommended file renaming of ref.wav and the other 3 files. Attempt to convert text file to an audiobook fails. See the terminal output below for full output.

**Commands to setup:**
```bash
git clone https://github.com/DrewThomasson/ebook2audiobook.git
cd ebook2audiobook
docker build . --platform linux/amd64 -t 'testimage/ebook2audiobook'
docker compose up -d
```

**Docker compose file:**
```yaml
version: "3.3"
services:
  ebook2audiobookxtts:
    image: testimage/ebook2audiobook
    #image: athomasson2/ebook2audiobook:latest
    platform: linux/amd64
    tty: true
    stdin_open: true
    ports:
      - 7860:7860
    command: python app.py
    environment:
      TZ: America/Chicago
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
        limits:
          memory: 32g # Uncomment to set a 4GB upper limit on system RAM usage by the container.
    volumes:
      - /mnt/pool1/docker/ebook2audiobook/tmp:/home/user/app/tmp
      - /mnt/pool1/docker/ebook2audiobook/audiobooks:/home/user/app/audiobooks
      - /mnt/pool1/docker/ebook2audiobook/models:/home/user/app/models
networks: {}
```

**Terminal output when attempting to use custom model with small text file for testing purposes.**
You can see where the custom model is loaded, then when the conversion is started it fails.
```
ebook2audiobook | Loading TTS xtts model from /home/user/app/models/__sessions/model-d893fccf-189c-42ff-a2ad-9dcc8d5f9b32/xtts/johnbanks, it takes a while, please be patient...
ebook2audiobook | 'TTSManager' object has no attribute 'coqui_tts_load_custom'
ebook2audiobook | Traceback (most recent call last):
ebook2audiobook |   File "/home/user/app/lib/functions.py", line 627, in convert_chapters_to_audio
ebook2audiobook |     tts_manager = TTSManager(session)
ebook2audiobook |                   ^^^^^^^^^^^^^^^^^^^
ebook2audiobook |   File "/home/user/app/lib/classes/tts_manager.py", line 71, in __init__
ebook2audiobook |     self.params['tts'] = self.coqui_tts_load_custom(self.model_path, self.config_path, self.vocab_path, self.session['device'])
ebook2audiobook |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
ebook2audiobook | AttributeError: 'TTSManager' object has no attribute 'coqui_tts_load_custom'
ebook2audiobook | Caught DependencyError: 'TTSManager' object has no attribute 'coqui_tts_load_custom'
ebook2audiobook | convert_chapters_to_audio() failed!
```
