### ISSUE TITLE
GPU is not available on your device (podman)

### ISSUE THREAD

**Issue by wutr** [DrewThomasson/ebook2audiobook#664]
**Script Mode**
- Podman

**Process Mode**
- Gradio GUI
  
**Operating System:**
Linux - Ubuntu 22.04

**Describe the bug**
Ebook2audiobook does not (want to) run on my nvidia GPU. Having read through [Program is runing on CPU and not GPU](https://github.com/DrewThomasson/ebook2audiobook/issues/7) after I encountered a similar issue, I haven't yet been able to find a solution.

I am trying to run ebook2audiobook under rootless podman, using the compose file provided with the image changed to the `latest` tag instead of `lite`. I have installed the nvidia-container-toolkit and that seems to work, because running: `podman run -it --rm docker.io/nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi` gives the expected output.

**Terminal log**
```
$ docker-compose up --force-recreate
Recreating ebook2audiobook_ebook2audiobook_1 ... done
Attaching to ebook2audiobook_ebook2audiobook_1
ebook2audiobook_1  | v25.3.22 full_docker mode
ebook2audiobook_1  | IPs available for connection:
ebook2audiobook_1  | ['127.0.0.1', '::1', '10.89.3.12', 'fe80::2c0a:87ff:fe3d:d90e%eth0']
ebook2audiobook_1  | Note: 0.0.0.0 is not the IP to connect. Instead use an IP above to connect.
ebook2audiobook_1  | * Running on local URL:  http://0.0.0.0:7860
ebook2audiobook_1  | 
ebook2audiobook_1  | To create a public link, set `share=True` in `launch()`.
ebook2audiobook_1  | Processing eBook file: 4-apr-test.txt
ebook2audiobook_1  | GPU is not available on your device!
ebook2audiobook_1  | Available Processor Unit: cpu
ebook2audiobook_1  | Running command: /usr/bin/ebook-convert /app/tmp/ebook-acae704e-8a63-4077-b017-dbff0bf6a920/736008a2170315f06700ecfe36d4e53b/4-apr-test.txt /app/tmp/ebook-acae704e-8a63-4077-b017-dbff0bf6a920/736008a2170315f06700ecfe36d4e53b/__4-apr-test.epub
```

**Comment by Leon-Sander** [comment]
Having the same problem in wsl with docker mode

**Comment by SouthofNorth** [comment]
Having the same issue with Gradio GUI on Win 10 with a NVIDIA GeForce GTX 1660 Super, with recently updated drivers.

**Comment by DrewThomasson** [comment]
Did you change 

```python
<<: *gpu-disabled
```

to 

```python
<<: *gpu-enabled
```

In the `docker-compose.yml`

**Comment by wutr** [comment]
Yep, I enabled that immediately. I also tried to circumvent it and run it with "1" GPU, but neither resulted in the GPU being used.

16 Apr 2025 03:53:48 Drew Thomasson ***@***.***>:

**Comment by SouthofNorth** [comment]
This may be a dumb question, but if I am using Gradio, launching from command line on windows, should editing the "docker-compose.yml" file work? I'm not running a docker container.

**Comment by DrewThomasson** [comment]
What happens if you use the GPU `docker run` command? 

for curiosity sake

**Comment by DrewThomasson** [comment]
Oh I think I figured it out, 

`podman` uses different syntax for GPU access.

idk try this, as the contents for `docker-compose.yml` instead

```
version: '3'

services:
  ebook2audiobook:
    # Available tags: latest (CUDA 11), cpu, rocm, cuda11, cuda12, xpu (x86 only), lite
    image: docker.io/athomasson2/ebook2audiobook:lite
    pull_policy: always
    entrypoint: ["python", "app.py", "--script_mode", "full_docker"]
    command: [] # Extra parameters can be added here
    tty: true
    stdin_open: true
    ports:
      - 7860:7860
    # Podman-specific GPU configuration
    device: "/dev/nvidia0:/dev/nvidia0"
    # Add all necessary GPU devices and drivers
    devices:
      - "/dev/nvidia0:/dev/nvidia0"
      - "/dev/nvidiactl:/dev/nvidiactl"
      - "/dev/nvidia-uvm:/dev/nvidia-uvm"
      - "/dev/nvidia-modeset:/dev/nvidia-modeset"
    # Environment variables for GPU access
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./:/app
```
