### ISSUE TITLE
Confusing error message when an ebooks_dir is empty

### ISSUE THREAD

**Issue by mrcoleman** [DrewThomasson/ebook2audiobook#679]
**Script Mode**
- Docker

**Process Mode**
- Headless

**Command Line (headless mode only)**
"--session","batchmode","--headless", "--ebooks_dir","/app/books", "--language", "eng","--voice","/app/clips/doki.mp3","--device","gpu", "--tts_engine", "xtts","--output_format","m4b","--output_dir","/app/audiobooks"

`e2a.yml`

```yaml
services:
  e2a:
    image: athomasson2/ebook2audiobook:cuda12-v25.3.22
    container_name: e2a
    volumes:
      - ./tmp:/app/tmp
      - ./audiobooks:/app/audiobooks
      - ./input_books:/app/books
      - ./voices:/app/clips
      - ./models:/app/models
    ports:
      - 7860:7860
    runtime: nvidia
    command: ["--session","batchmode","--headless", "--ebooks_dir","/app/books", "--language", "eng","--voice","/app/clips/doki.mp3","--device","gpu", "--tts_engine", "xtts","--output_format","m4b","--output_dir","/app/audiobooks"]
   
```
  
**Operating System:**
 - Windows

**Describe the bug**
When the ebooks_dir is empty a stack dump is returned instead of an error message.

**Terminal log**
```powershell
PS D:\Projects\unmainc> docker compose -f .\e2a.yml up
[+] Running 1/1r Desktop   o View Config   w Enable Watch
 ✔ Container e2a  Recreated                                                                                                                       0.2s 
Attaching to e2a
e2a  | v25.3.22 full_docker mode
e2a  | Traceback (most recent call last):
e2a  |   File "/app/app.py", line 296, in <module>
e2a  |     main()                                                                                                                                      
e2a  |   File "/app/app.py", line 264, in main                                                                                                         
e2a  |     progress_status, passed = convert_ebook_batch(args)
e2a  |                               ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                         
e2a  |   File "/app/lib/functions.py", line 1240, in convert_ebook_batch                                                                               
e2a  |     return progress_status, passed                                                                                                              
e2a  |            ^^^^^^^^^^^^^^^
e2a  | UnboundLocalError: cannot access local variable 'progress_status' where it is not associated with a value                                       
e2a exited with code 1
```
